name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  twilio_video:
    path: ../twilio_video

  # The plugin has reached a stable API.
  # They guarantee that version 1.0.0 will be backward compatible with 0.5.y+z.
  # Use below dependency constraint to allow a smoother ecosystem migration.
  shared_preferences: ">=0.5.7+3 <2.0.0"

  # Request permission to access camera and microphone
  permission_handler: 5.0.1+1

  equatable: 1.2.0
  provider: 4.1.3
  bloc: 5.0.0
  flutter_bloc: 5.0.0
  animations: 1.1.1
  meta: 1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
