name: shrine
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  flutter_localized_locales: ^1.1.1
  cupertino_icons: ^1.0.0
  rally_assets: ^2.0.0
  meta: ^1.1.8
  scoped_model: ^1.1.0
  shrine_images: ^1.1.2
  flare_dart: ^2.3.4
  flare_flutter: ^2.0.2
  url_launcher: ^5.6.0
  vector_math: ^2.0.8
  shared_preferences: ^0.5.4
  collection: ^1.14.0
  flutter_gallery_assets: ^0.2.6
  package_info: ^0.4.0
  google_fonts: ^1.0.0
  flutter_staggered_grid_view: ^0.3.0
  animations: ^1.1.2
  provider: ^4.3.2
  adaptive_breakpoints: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:
  path:
  args:
  grinder: ^0.8.0
  intl_translation:
  pedantic: ^1.9.0
  string_scanner: ^1.0.5

flutter:
  assets:
    - packages/flutter_gallery_assets/fonts/GalleryIcons.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Regular.ttf
    - packages/shrine_images/diamond.png
    - packages/shrine_images/slanted_menu.png
    - packages/shrine_images/0-0.jpg
    - packages/shrine_images/1-0.jpg
    - packages/shrine_images/2-0.jpg
    - packages/shrine_images/3-0.jpg
    - packages/shrine_images/4-0.jpg
    - packages/shrine_images/5-0.jpg
    - packages/shrine_images/6-0.jpg
    - packages/shrine_images/7-0.jpg
    - packages/shrine_images/8-0.jpg
    - packages/shrine_images/9-0.jpg
    - packages/shrine_images/10-0.jpg
    - packages/shrine_images/11-0.jpg
    - packages/shrine_images/12-0.jpg
    - packages/shrine_images/13-0.jpg
    - packages/shrine_images/14-0.jpg
    - packages/shrine_images/15-0.jpg
    - packages/shrine_images/16-0.jpg
    - packages/shrine_images/17-0.jpg
    - packages/shrine_images/18-0.jpg
    - packages/shrine_images/19-0.jpg
    - packages/shrine_images/20-0.jpg
    - packages/shrine_images/21-0.jpg
    - packages/shrine_images/22-0.jpg
    - packages/shrine_images/23-0.jpg
    - packages/shrine_images/24-0.jpg
    - packages/shrine_images/25-0.jpg
    - packages/shrine_images/26-0.jpg
    - packages/shrine_images/27-0.jpg
    - packages/shrine_images/28-0.jpg
    - packages/shrine_images/29-0.jpg
    - packages/shrine_images/30-0.jpg
    - packages/shrine_images/31-0.jpg
    - packages/shrine_images/32-0.jpg
    - packages/shrine_images/33-0.jpg
    - packages/shrine_images/34-0.jpg
    - packages/shrine_images/35-0.jpg
    - packages/shrine_images/36-0.jpg
    - packages/shrine_images/37-0.jpg

  # Adds code generation (synthetic package) support 
  generate: true
  uses-material-design: true
  fonts:
    - family: GalleryIcons
      fonts:
        - asset: packages/flutter_gallery_assets/fonts/GalleryIcons.ttf
