name: ad_stream
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BASE
  quiver: 2.1.3
  collection: 1.14.13
  equatable: 1.2.3
  bloc: 6.0.1
  meta: 1.1.8
  rxdart: ">=0.24.1 <2.0.0"

  # DI
  #
  # An utility provides a Dependency Injection library.
  # see more at google/inject.dart
  inject:
    path: ../vendor/inject

  # DEVICE PLUGINS
  #
  # The plugin has reached a stable API.
  # They guarantee that version 1.0.0 will be backward compatible with 0.5.y+z.
  # Use below dependency constraint to allow a smoother ecosystem migration.
  shared_preferences: ">=0.5.7+3 <2.0.0"

  # Request permission to access camera and microphone
  permission_handler: 5.0.1+1

  # to 1) get current location of device
  #    2) calculate the distance (in meters) between two geo coordinates;
  geolocator: 5.3.2+2

  # UI ENHANCEMENT
  animations: 1.1.1

  # STATE MANAGEMENT
  provider: 4.1.3

  # UTILITY
  faker: 1.2.1

  # allow persisting sample gps values as csv
  csv: 4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  inject_generator:
    path: ../vendor/inject_generator

  build_runner: 1.7.3
  test: ^1.15.2
  mockito: ^4.1.1

  # FakeAsync fires all asynchronous events that are scheduled for that time period without
  #  actually needing the test to wait for real time to elapse.
  fake_async: ^1.1.0

flutter:
  uses-material-design: true

  # sample background for ads
  assets:
    - assets/p1.jpg
    - assets/p2.jpg
    - assets/p3.jpg
