name: admin_template_generator
description: A new Flutter package.
version: 0.0.1

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^0.39.8
  build: ^1.2.2
  code_builder: ^3.2.1
  meta: ^1.1.8
  source_gen: ^0.9.5
  collection: ^1.14.11
  admin_template_annotation:
    path: ../admin_template_annotation

dev_dependencies:
  test: ^1.11.0
  build_test: ^0.10.12
  dart_style: ^1.3.3
