name: ad_bloc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BASE
  quiver: 2.1.3
  collection: 1.14.13
  equatable: 1.2.3
  bloc: 6.0.1
  flutter_bloc: 6.0.5
  meta: 1.1.8
  tuple: 1.0.3
  rxdart: ">=0.24.1 <2.0.0"
  stream_transform: 1.2.0

  # DEVICE PLUGINS
  #
  # The plugin has reached a stable API.
  # They guarantee that version 1.0.0 will be backward compatible with 0.5.y+z.
  # Use below dependency constraint to allow a smoother ecosystem migration.
  shared_preferences: ">=0.5.7+3 <2.0.0"

  # Request permission to access camera and microphone
  permission_handler: 5.0.1+1
  
  # Provide power state.
  battery: 1.0.5

  # to 1) get current location of device
  #    2) calculate the distance (in meters) between two geo coordinates;
  geolocator: 5.3.2+2

  # display video
  video_player: '>=0.10.12+2 <2.0.0'

  # UI ENHANCEMENT
  animations: 1.1.1

  # STATE MANAGEMENT
  provider: 4.1.3

  # UTILITY
  faker: 1.2.1
  # gen face id
  crypto: 2.1.5

  # allow persisting sample gps values as csv
  csv: 4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  test: ^1.15.2
  bloc_test: ^7.0.4
  mockito: ^4.1.1

  # A Gherkin / Cucumber parser
  flutter_gherkin: ^1.1.8+8

  # FakeAsync fires all asynchronous events that are scheduled for that time period without
  #  actually needing the test to wait for real time to elapse.
  fake_async: ^1.1.0

flutter:
  uses-material-design: true
